// GENERATED by `tdk migrate` from a migration model (ADR-0026).
//
// This is authoring-v2 source you now OWN: the printer produced the first version,
// and from here people own the file (generate-once). Regenerating OVERWRITES it.
// Anything the printer could not translate is a flagged TODO(migration) — see the
// sibling migration-report.json for the full account. Nothing was dropped in silence.

import { all, defineTemplate, derive, effect, p, page, raw } from "@tdk/core";
// Action mapping (org-supplied): legacy:oven-booking:create-work-order -> createWorkOrder.
// Resolver convention (org-supplied): roster lookups -> the maintenanceRoster marker.
import { createWorkOrder, maintenanceRoster } from "./pack.ts";

// --- Fields (one const per question; page tags become the pages TOC) -------------
export const bakeryCode = p.choice({ BK1: "Riverside", BK2: "Old Town", BK3: "Harbourfront" }, { title: "Bakery site", required: true });
export const ovenId = p.string({ title: "Oven asset ID", required: true });
export const ovenCount = p.number({ title: "How many ovens?", minimum: 1 });
export const faultType = p.choice({ heating: "Heating", door: "Door", controls: "Controls", other: "Other" }, { title: "Fault type", required: true });
export const faultDetail = p.string({ title: "Describe the fault", uiWidget: "textarea" }).showWhen(faultType.is("other"));
export const severity = p.choice({ low: "Low", normal: "Normal", urgent: "Urgent" }, { title: "Severity", required: true });
export const urgentReason = p.string({ title: "Why is this urgent?" }).showWhen(severity.is("urgent"));
export const escalate = p.boolean({ title: "Escalate to the facilities lead?" }).showWhen(all(faultType.is("other"), severity.in(["normal", "urgent"])));
export const partNumbers = p.array({ title: "Replacement part numbers" });

// --- Logic node 'job-summary' -> a derive ----------------------------------------
export const jobSummary = derive("job-summary", { ovenId, bakeryCode }, (i) => `Oven ${i.ovenId} at ${i.bakeryCode}`);

// --- Logic node 'sla-hours' -> a derive ------------------------------------------
export const slaHours = derive("sla-hours", { severity }, (i) => i.severity === "urgent" ? 4 : i.severity === "normal" ? 24 : 72);

// --- Logic node 'parts-list' -> a derive -----------------------------------------
export const partsList = derive("parts-list", { partNumbers }, (i) => i.partNumbers.map((part) => `OV-${part}`));

// --- Logic node 'escalation-note' -> a derive ------------------------------------
export const escalationNote = derive("escalation-note", { jobSummary, severity }, (i) => `Re: ${i.jobSummary} (severity ${i.severity})`);

// --- Logic node 'priority-code' — FLAGGED verbatim expression --------------------
// TODO(migration): the model could not express this in the logic IR, so its
//   source is preserved verbatim. Re-author it as a derive (or wire it into the
//   right step) before relying on it. See migration-report.json.
//   language: jsonata
//   source: $count(partNumbers) > 3 ? "bulk" : "standard"
const priorityCode = raw`TODO(migration) unported expression: priority-code`;

// --- Lookup 'assignee' — FLAGGED, see migration-report.json ----------------------
// TODO(migration): external reference preserved verbatim from the legacy export.
//   source: roster://maintenance-team?site={bakeryCode}
// Emitted against the org's resolver convention. VERIFY the resolver exists and
// returns the expected shape before you rely on it.
const assignee = maintenanceRoster({ site: bakeryCode });

// --- Effect 'submit-request' via the mapped pack helper --------------------------
export const submitRequest = createWorkOrder("submit-request", { title: jobSummary, site: bakeryCode, oven: ovenId, sla: slaHours, parts: partsList, note: escalationNote, priority: priorityCode, detail: faultDetail.ref.orElse(""), assignee });

// --- Effect 'notify-facilities' — FLAGGED, unmapped legacy action ----------------
// TODO(migration): unmapped legacy action legacy:oven-booking:notify.
//   Supply an action mapping (actionRef -> a pack helper) to emit a typed helper
//   call, or keep this direct effect() and confirm the action id + input shape.
export const notifyFacilities = effect("notify-facilities", "legacy:oven-booking:notify", { input: { summary: jobSummary, reason: urgentReason.ref.orElse("") } }).when(severity.is("urgent"));

export default defineTemplate({
  id: "request-oven-maintenance",
  title: "Request oven maintenance",
  description: "Raise a maintenance work order for a bakery oven.",
  type: "service",
  tags: ["bakery", "oven", "maintenance"],
  owner: "team-bakery",
  extraSpec: { catalog_metadata: { category: "Facilities", lead_time_days: "3", fulfilment_team: "Bakery Facilities Guild", cost_centre: "OVEN-OPS", escalation: { channel: "#oven-support", pager: "facilities-oncall" } } },
  // Pages ARE the ordered table of contents; ui:order is inferred per page.
  pages: [
    page("Site", { bakeryCode, ovenId, ovenCount }),
    page("Fault", { faultType, faultDetail, severity, urgentReason, escalate }),
    page("Parts", { partNumbers }),
  ],
  effects: [submitRequest, notifyFacilities],
  output: {
    workOrderId: submitRequest.output.body.id,
    sla: slaHours,
  },
});
