// GENERATED by `tdk migrate` from the model's exampleValues (ADR-0026).
//
// A born-testable baseline: one happy-path scenario. `tdk test` writes the first
// snapshot from this; edit freely — this is your file now.

import type { ExecuteFixture } from "@tdk/core";

export const scenarios = [
  {
    name: "example — happy path",
    branches: ["other", "urgent"],
    fixture: {
      parameters: {
        bakeryCode: "BK1",
        ovenId: "OV-4471",
        ovenCount: 2,
        faultType: "other",
        faultDetail: "Door seal warped, heat escaping",
        severity: "urgent",
        urgentReason: "Production line stopped",
        escalate: true,
        partNumbers: ["A1", "B2"],
        cakeLine: { id: "cake-line-sourdough", name: "Sourdough loaf" },
      },
      steps: {
        "submit-request": { output: { body: { id: "submit-request-id" } } },
        "notify-facilities": { output: {} },
      },
    } satisfies ExecuteFixture,
  },
];
